### PR TITLE
Per 9184 build results page after ssearch

### PR DESCRIPTION
**Pull request by crisnicandrei**
This pull request adds the new design to the search results -> please be advised that this is still work in progress but i would like some input about the progress so far while i am waiting for the remaining icons 

This is the second PR that should be reviewed for the public search. 

This is still using dummy data so the search does not work on this pr yet

### CODE REVIEW

**Comment by meisekimiu** [comment]
While handling the actual API requests is being handled in #202, there is still some placeholder data being used in the design here (specifically data on the archive profile). Is that going to be done in this branch after #202 is merged?

**Comment by meisekimiu** [comment]
I'm talking about the data on the archive profile, and not the search results. This is a screenshot running on #202

**Comment by crisnicandrei** [comment]
@meisekimiu you are right! I will fix it this evening so you can still review it today

**Comment by crisnicandrei** [comment]
@meisekimiu I have fixed that, can you please check again?

**Comment by meisekimiu** [comment]
Can you update the line that lists the archive's birth date and birthplace?


As you can see in the screenshot, the location is blank and makes this line look weird. Earlier I didn't have a birth date listed on the profile either and it listed it as  just "Born on in".

I would assume if the user doesn't have a birth (or "established" if they're a group/organization archive) date or place it should hide that part entirely. Something like this:
<table>
<thead>
<tr>
<th>Birth Date</th>
<th>Birth Place</th>
<th>Profile Text</th>
</tr>
</thead>
<tbody>
<tr>
<td>"2023-05-11"</td>
<td>"Place"</td>
<td>Born on 2023-05-11 in Place</td>
</tr>
<tr>
<td>"2023-05-11"</td>
<td><em>undefined</em></td>
<td>Born on 2023-05-11</td>
</tr>
<tr>
<td><em>undefined</em></td>
<td>"Place"</td>
<td>Born in Place</td>
</tr>
<tr>
<td><em>undefined</em></td>
<td><em>undefined</em></td>
<td><em>(text is not displayed)</em></td>
</tr>
</tbody>
</table>
(With the "Born" being substituted for "Established" for group/organization/nonprofit archives)

**Comment by crisnicandrei** [comment]
@meisekimiu Thank you! I have made the changes

**Comment by meisekimiu** [comment]
Thanks for making that change!
I have found a few other small styling issues:

* Can we separate the formatting between the "on" or "in" in the message and the actual date?

I feel like this should look like "Born on **May 13, 2023**" rather than "Born **on May 13, 2023**"
* At certain screen widths, the layout of the public archive / public profile pages seems to break. This is on Google Chrome at a width of about 960px.

* At certain screen widths, the various items/records/folders in the public archive look very small. If I make the screen smaller they actually get bigger somehow.

You can see how the names can't even be displayed. This is about 1920px screen width at normal zoom level.

**Comment by crisnicandrei** [comment]
Screenshot 2023-05-15 at 11 53 05
@meisekimiu this is what it looks like for me at 1920 px width

**Comment by crisnicandrei** [comment]
@meisekimiu the other comments have been fixed, maybe could you tell me the exact width and height please?

**Comment by meisekimiu** [comment]
This PR has been combined with the other public search PRs into #226 for convenience. We'll close this PR once that one gets merged, but I want to keep this PR open just in case any commits/issues got lost in the process of combining all of the PRs.

**Comment by meisekimiu** [comment]
Closing this since #226 was merged.

**Pull request closed without merging**
