### PR TITLE
Add Postgres Migration Downtime Banner

### PR DESCRIPTION
**Pull request by meisekimiu**
Warn users ahead of time of our scheduled maintenance for the Postgres migration on production.

### CODE REVIEW

**Review by liam-lloyd — APPROVED** [review]

**Comment by meisekimiu** [comment]
Updated the date format, since it was working in Chrome but not in Firefox!

**Review by cecilia-donnelly — COMMENTED** [review]
I'm getting errors on compiling this, I think because of the Angular 12 -> 13 upgrade. Maybe it needs to be rebased? 

(Specifically I see errors about no "AngularFireDatabase.")

**Review by cecilia-donnelly — APPROVED** [review]
Looks good on Firefox now!

**Comment by meisekimiu** [comment]
I can't approve my own PR, but these changes look good so I'm going to merge!

**Pull request merged**
