### PR TITLE
PER-9807-Design changes to archive invite

### PR DESCRIPTION
**Pull request by crisnicandrei**
Design changes requested to the invite to archive screen

### CODE REVIEW

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
Looking good!

- When someone clicks "Accept" the text should change to say "Accepted" not "Accept"
- The last page of onboarding should list all new archives that the member accepted the invitation to. Right now, it looks like it only lists one, even though multiple were accepted (I checked in my account afterwards, so it does look like it's working as expected. They're just not listed on that final page). @crisnicandrei is this addressed in another ticket already? If not, I can create a ticket.
- Do you also mind checking with @tiberiuVSP  on the size of the help text? It looks small and a little hard to read. If the size of the text is correct with the design, Tibi might want to think about adjusting it to a larger size so it's more readable.

**Comment by crisnicandrei** [comment]
@k8lyn6 that is not addressed in another ticket. I can make one tomorrow of you don't have time today😀

**Comment by k8lyn6** [comment]
@crisnicandrei [here's the new ticket!](https://permanent.atlassian.net/browse/PER-9891) Thanks! Taking a look at your changes to this PR now.

**Review by k8lyn6 — APPROVED** [review]
Changes look good! @crisnicandrei before you merge this, do you mind checking on the font size with @tiberiuVSP ?

**Comment by crisnicandrei** [comment]
@k8lyn6 I have checked the fonts with him, and made a few changes

**Pull request merged**
