### PR TITLE
PER-9892 Add opt in option to the sign up page

### PR DESCRIPTION
**Pull request by crisnicandrei**
Add checkbox for email opt in option to the signup page

@k8lyn6 I kept the checkboxes in the front, because it was never mentioned to use the iOS looking ones. Should I change them to those?

### CODE REVIEW

**Review by meisekimiu — APPROVED** [review]

**Comment by k8lyn6** [comment]
@crisnicandrei I'd say to do whatever is in the design unless it poses a problem. Do we have those already in the app somewhere? Will it be a lot of effort to use the sliders?

**Comment by crisnicandrei** [comment]
@k8lyn6  we do have them! I just wanted to check with you about this firat. I will change them tomorrow! Thanks!

**Comment by crisnicandrei** [comment]
@k8lyn6 I have changed the checkboxes to toggles!

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
Looking good so far! I noticed that the toggles look a little different when turned off. From the design, it looks like the bubble of the toggle should be more transparent, so you can see it's a toggle. I've attached two screenshots to show the difference. If you have any questions about it, I'd ask Tibi or Natalie.
Screenshot 2024-11-01 at 9 48 41 AM
Screenshot 2024-11-01 at 9 48 31 AM

The API calls look like they're working correctly to Mailchimp and getting tagged correctly. Thanks Andrei!

**Comment by crisnicandrei** [comment]
@k8lyn6 pushed the changes. Thank you!

**Review by k8lyn6 — APPROVED** [review]
Yep, that's better. Thanks for the quick change!

**Pull request merged**
