### PR TITLE
PER-8400-toggle-person-info-public-archive

### PR DESCRIPTION
**Pull request by crisnicandrei**
PER-8400-toggle-person-info-public-archive
Added a chevron that expands the profile information on mobile devices.

Steps to test:

1.Go to any public archive on mobile view.
2. Click the arrow expanding the information

### CODE REVIEW

**Review by meisekimiu — APPROVED** [review]

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
I'm so sorry for the delay! I think when you switch over to the archive profile, we don't need a drop down because the user is there to see the profile and it isn't getting in the way of anything.

**Comment by crisnicandrei** [comment]
@k8lyn6 did the changes!

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
I don't know if it's something on my end, but it looks like the "Established" and the summary section don't immediately show up unless you click to the archive and then back to the profile. It also looks like the "see more" isn't working. Here's a video to show you what I mean.

https://github.com/PermanentOrg/web-app/assets/16201121/5090af06-35e3-44cf-b732-3c1b5696d0a5

**Comment by crisnicandrei** [comment]
@k8lyn6 thanks! I found the issue and fixed it.

**Review by k8lyn6 — APPROVED** [review]
Looks good now!

**Pull request merged**
