### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by crisnicandrei**
More changes to the what's important to you screen

### CODE REVIEW

**Review by meisekimiu — APPROVED** [review]

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
I think most of these changes look good! 

One small thing: When the screen expands, the progress bar should probably stop expanding at some point and stay aligned with the chips and text below, and any extra space should just be filled with the blue background on the right and left sides.

**Comment by crisnicandrei** [comment]
@k8lyn6 thanks! I have added a max-width to the progress bar, let me know if this works or it should be less?

**Comment by yeslikesolo** [comment]
QA Notes:
The goal is to move "Let's set some goals" component to the right and fill the spacing for screens larger than 1440px. Two possible solutions:

- Increase spacing between "Chart your path" and "Let's set some goals" div boxes.
- If possible, adjust width of "let's set some goals" component to auto flex based on the width of the screen

Let me know if I can clarify anything!

Screenshot 2024-09-19 at 1 38 35 PM

**Comment by yeslikesolo** [comment]
Another note:
You can see the blue background isn't moving dynamically with the screen. The white shows up on the right side behind the selection choices when I open and close the screen. The left side removes the blue margin and "Chart your path" stays flushed against the side. This issue is occurring at ~960px? (I can't truly tell my screen size, so this is a guess.) 

https://github.com/user-attachments/assets/c515f2b8-ef20-42c5-8709-bdef54a513e5

**Comment by yeslikesolo** [comment]
"Tell us what's important to you" font seems to be bolded differently than previous header text. Please change to match "chat your path to success" font settings! Thank you (:

Screenshot 2024-09-19 at 2 09 07 PM

**Comment by crisnicandrei** [comment]
@yeslikesolo pushed the changes, but could you explain the auto flex part to me please?

**Comment by k8lyn6** [comment]
@yeslikesolo do you mind continuing to work with Andrei on this?

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
Small change -- I think the text and icons on the buttons are supposed to be centered according to the design. Once you've changed that, let's merge it!

**Comment by crisnicandrei** [comment]
@k8lyn6 done!

**Review by k8lyn6 — APPROVED** [review]
Looks good!

**Pull request merged**
