### PR TITLE
Changed the image resolution for the zooming library

### PR DESCRIPTION
**Pull request by crisnicandrei**
I have changed the image in the library component, making it use the highest resolution available

### CODE REVIEW

**Review by cecilia-donnelly — CHANGES_REQUESTED** [review]
I would use the `fileurl` under the `FileVO` since that's the full image. Even the larger thumbnail is likely lower quality than the original, and since we want to be able to zoom in we want the absolutely highest quality.

**Comment by crisnicandrei** [comment]
@meisekimiu @cecilia-donnelly I have found a way to fix the tests

**Review by meisekimiu — APPROVED** [review]

**Comment by crisnicandrei** [comment]
@cecilia-donnelly can i merge this?

**Review by cecilia-donnelly — APPROVED** [review]
Yes, looks good! Thanks for making this change.

**Pull request merged**
