### PR TITLE
PER-9890-switch-folder-item-on-share-view

### PR DESCRIPTION
**Pull request by crisnicandrei**
Display corresponding item in case shared file is a record or a folder

steps to test:

Record case:
Share a record with an email that does not have a Permanent account
Sign up with that email
On the onboarding page, the file icon should be the one for records.

Folder case:
Share a folder with an email that does not have a Permanent account
Sign up with that email
On the onboarding page, the file icon should be the one for folders.

### CODE REVIEW

**Review by meisekimiu — APPROVED** [review]

**Review by yeslikesolo — CHANGES_REQUESTED** [review]
QA Notes:
I was unable to see the folder or record of the shared material on the onboarding screen.
Screenshot 2024-10-24 at 2 47 44 PM
Screenshot 2024-10-24 at 2 49 33 PM

**Comment by crisnicandrei** [comment]
@yeslikesolo which steps did you take to reproduce this? You should access the url from your email first after sharing an item😄. Maybe I missed that sorry!

**Comment by yeslikesolo** [comment]
@crisnicandrei Gotcha! Just retested both the folder case and record case - they work great! Thanks Andrei for the speedy work (:

**Comment by crisnicandrei** [comment]
@yeslikesolo please don't forget to approve so i can merge it😄

**Review by yeslikesolo — APPROVED** [review]

**Comment by yeslikesolo** [comment]
@crisnicandrei whoops, sorry! Just changed it (:

**Pull request merged**
