### PR TITLE
Per 9752 add aditional mixpanel events

### PR DESCRIPTION
**Pull request by crisnicandrei**
This PR adds the new mixpanel events to the web-app

@meisekimiu, @k8lyn6 it seems there are 2 events now on the promo page, should we keep both?

### CODE REVIEW

**Comment by meisekimiu** [comment]
We might want to get rid of the duplicate entry, though I'll leave that up to the experience team.

**Review by yeslikesolo — CHANGES_REQUESTED** [review]
Looks like we are still missing the following events:
- Page View: Public Workspace
- Page View: Shared Workspace
- Page View: Public Gallery
- Page View: Redeem Gift
- Click: Share
- Click: Copy link after publishing a file

Yes, please delete the duplicates! For example, "Email" and "email" are both on there. Please use "Email" only and delete the other duplicate.

**Comment by crisnicandrei** [comment]
@yeslikesolo that is strange. I have tested them and they were working. Will re-test.

**Comment by yeslikesolo** [comment]
Awesome, just tested and Public Workspace is now working! Let me know when we are able to get the rest of the events updated and I'll do another test. Thanks @crisnicandrei! :D

**Comment by crisnicandrei** [comment]
@yeslikesolo they should be working. They were working for me. Also I did not get the "email" and "Email" duplicate? The duplicate events are on redeem gift page

**Comment by yeslikesolo** [comment]
@crisnicandrei I'm not seeing the events below on Mixpanel. They're not showing up when I just tested right now. I looked through all Lexicon events on Mixpanel to see if it could be under a different name or action, too. 

- Page View: Shared Workspace
- Page View: Public Gallery
- Page View: Redeem Gift
- Click: Share
- Click: Copy link after publishing a file

**Comment by crisnicandrei** [comment]
@yeslikesolo Open public gallery
image

**Review by yeslikesolo — APPROVED** [review]
Just retested, everything is visible and working now in events ! Thank you Andrei (:

**Pull request merged**
