### PR TITLE
Added the missing mixpanel events

### PR DESCRIPTION
**Pull request by crisnicandrei**
This pr adds the missing mixpanel events from the confluence document.

I have decided to make one big pr instead of many small ones because I have added 2 new methods to the mixpanel and device services which i needed, so instead of branching multiple times I made one bigger pr.

### CODE REVIEW

**Comment by crisnicandrei** [comment]
@meisekimiu you are right, I forgot to remove the imports from some places

**Comment by crisnicandrei** [comment]
@meisekimiu in the future i will keep prs smaller, but i needed that service method, and I did not want to keep rebranching for all the other prs.

**Comment by meisekimiu** [comment]
The pull request itself doesn't need to be smaller, I just think separating each event into its own git commit within the PR would keep things more organized.

**Comment by crisnicandrei** [comment]
@meisekimiu i get it now! Thanks!

**Review by k8lyn6 — APPROVED** [review]
Everything looks good now! Thanks!

**Pull request merged**
