### PR TITLE
design changes to final onboarding screen

### PR DESCRIPTION
**Pull request by crisnicandrei**
@k8lyn6 the icons work fine for me

I also need a link for the new underlined text:)  Thanks!

### CODE REVIEW

**Review by yeslikesolo — COMMENTED** [review]
Screenshot 2024-11-08 at 2 17 34 PM

1. Looks like the icons aren't working for me
2. Clicking on the underlined link "viewing our help articles here." takes me back to the log in screen. I think it should take us to the Knowledge Base instead ? (Idk what the link was before)

**Comment by crisnicandrei** [comment]
@yeslikesolo can you paste it here please so i can add it?

**Comment by k8lyn6** [comment]
@crisnicandrei the link should take you to https://permanent.zohodesk.com/portal/en/kb/permanent-legacy-foundation

**Comment by crisnicandrei** [comment]
@k8lyn6 @meisekimiu @yeslikesolo updated the url

**Comment by crisnicandrei** [comment]
@yeslikesolo pushed the changes

**Review by yeslikesolo — APPROVED** [review]
Yay, works great. Thanks @crisnicandrei & @meisekimiu !

**Pull request merged**
