### PR TITLE
Design changes to the name archive screen

### PR DESCRIPTION
**Pull request by crisnicandrei**
This pull request adds the changes requested in the ticket to the new name archive screen

### CODE REVIEW

**Review by meisekimiu — APPROVED** [review]

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
Looking good! A few notes:

- The error symbol is still hiding behind the word "Archive"
- Only "personal" should be bolded in the left side text
- All the items on the left side (Permanent logo, status bar, and text) should align when screen is resized. Currently, they don't look quite aligned
- I can't see the Permanent logo image -- it's broken for me (not sure if this is a me problem or something else)
- The back and next buttons should be the same size
- When the viewport switches to a mobile size, can we remove some of the space between the archive name field and the buttons, so you don't have to scroll as much?

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
Looks like most things are fixed! Two questions:

1. It's really hard to tell, but is only the archive type bolded on the left side? "Create your" and "Archive" should be normal font, and "Personal" or "Family History" or whatever should be bolded.
2. I still can't see the Permanent logo image. I think we're okay to merge this once you address the first issue, but we'll want to double check it's working before release.

**Comment by crisnicandrei** [comment]
@k8lyn6 can you check now? It should be bolder, this is the boldest I can do. And regarding the image, it works for me so I really don't know what is going on

**Comment by k8lyn6** [comment]
@crisnicandrei Compared to the design, the boldness just looks different. Are you using the font from the design (I think it's called Usual).

**Comment by crisnicandrei** [comment]
@k8lyn6 did some changes

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
Looks good! Just one minor change -- the buttons are the right size, but the text and icon should be centered.

**Comment by crisnicandrei** [comment]
@k8lyn6 pushed the changes!

**Review by k8lyn6 — APPROVED** [review]
I think this looks good! Also checked old onboarding to make sure that nothing here changes anything about old onboarding, and it looks fine.

**Pull request merged**
