### PR TITLE
design changes to the create archive for me screen

### PR DESCRIPTION
**Pull request by crisnicandrei**

### CODE REVIEW

**Review by meisekimiu — APPROVED** [review]

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
Looks good! Small thing: the archive icon is broken for me on this page. I've attached a screenshot. Could you look into this? I tried on both Chrome and Firefox.
Screenshot 2024-11-26 at 1 29 25 PM

**Comment by crisnicandrei** [comment]
@k8lyn6 the icons work well for me locally! Which is the env you are testing on and how can I access it? It seems there might be a problem with how the image paths are handled on it so I would like to take a look, as this is not the first time it happens to the Experience Team

**Comment by k8lyn6** [comment]
@crisnicandrei I am testing on the `dev` environment, which you can access at [dev.permanent.org/app/auth/login](dev.permanent.org/app/auth/login) (you can just create a test account there).

**Review by k8lyn6 — APPROVED** [review]
I think we made the above issue a separate ticket so I'm approving this PR!

**Pull request merged**
