### PR TITLE
PER-9259-fix pdf display on mobile

### PR DESCRIPTION
**Pull request by crisnicandrei**
I have fixed the pdf display on mobile by adding an additional check and removing a css rule

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204725642430373

### CODE REVIEW

**Comment by crisnicandrei** [comment]
I have also assigned @k8lyn6 just now

**Review by k8lyn6 — CHANGES_REQUESTED** [review]
Oops, I just realized this didn't go through code review yet -- sorry for jumping in too fast! However, I did take a look and it looks like PDFs are no longer showing up in the new zoom reader, but it's only showing the first page of the PDFs in a mobile browser. It also doesn't look like a document viewer. It seems to work fine in a desktop browser at different sizes, though (i.e. shows up properly in a document viewer and you can see all pages of the PDF).

**Comment by crisnicandrei** [comment]
@k8lyn6 could you please send me some screenshots of how it used to look before?

**Comment by k8lyn6** [comment]
@crisnicandrei I don't think I have any screenshots available of what it looked like before. To be honest, it could have been broken before we implemented the new zoom feature -- I'm not entirely sure. But ideally, the PDF would open like it does in a desktop browser or even the mobile app so you can view all the pages.

**Comment by crisnicandrei** [comment]
@k8lyn6 

https://github.com/PermanentOrg/web-app/assets/62384997/16a7b824-d97e-429b-bb14-554e7853aeea

This is how it looks like to me, isn't this correct? If not can you please point out what needs to be changed because I couldn't understand. Thanks

**Review by cecilia-donnelly — APPROVED** [review]
This looks correct to me. I can scroll the pdf in the mobile-sized browser on Firefox and can still open and zoom an image.

**Comment by k8lyn6** [comment]
@crisnicandrei it looks like it works fine in a web browser collapsed to mobile view, but if you look on an actual mobile browser, this is what happens. Not sure what's different about the two, but I tried on Safari and Chrome on my iPhone after deploying this branch to dev.

https://github.com/PermanentOrg/web-app/assets/16201121/4d5bb81e-31ad-4051-a0ce-42d83e623d67

**Review by k8lyn6 — APPROVED** [review]
This looks like it's working as we decided in Slack.

**Pull request merged**
